- name: install dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - curl
    - python-docker
- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh
- name: give docker swap and ulimit capabilities
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    backrefs: true
    line: 'GRUB_CMDLINE_LINUX="\1 cgroup_enable=memory swapaccount=1"'
  notify:
    - update grub
- name: add vagrant user to docker group
  user:
    name: vagrant
    append: yes
    groups: docker
- name: add proxy to docker env if needed
  lineinfile:
      dest: /etc/default/docker
      state: present
      line: "http_proxy=\"{{ ansible_env.http_proxy }}\"\nhttps_proxy=\"{{ ansible_env.https_proxy }}\""
  when: ansible_env.http_proxy is defined
- name: configure http proxy if needed
  lineinfile:
      dest: /lib/systemd/system/docker.service
      state: present
      insertafter: ExecStart
      line: EnvironmentFile=-/etc/default/docker
  when: ansible_env.http_proxy is defined
# we need this right away, so we cannot use a handler here
- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_env.http_proxy is defined
- name: reload docker
  service: name=docker state=restarted
  when: ansible_env.http_proxy is defined
