dist: trusty
sudo: required
jdk: oraclejdk8
services:
- docker
script:
- bash test/travis-bin/run-tests.sh
- bash test/travis-bin/sonar.sh
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
addons:
  sonarqube:
    token:
      secure: qBNJ5FgLHRi6iam3Ytr6UtwX5YJlymRVxz7qaGzI2RPEgqg+tKVDiV8pxWn2Zmj3zoUaduIc2CbRdteSL4ZsTSV5Q5zymQlGYTDJWKcm0QSinXAW0xh6Lry99rtHMuFu240fa2gAhKyNETVgfY7Y7rXMQD6p32ATDtcCBd8jAy5SAhgxOki7MzpxXH6higyCVtuK8MSSqY+Q9D8vJrjNfRYEPb9KFUX4kXvuH1b0+ptwAeOKpnvmnZUiYzZ8jHT0kuhzCIMK3QwylFx+ApQmE3DLsXc1Y0wPOkjDEXsZmIYiPZy6az92ItpkEJr9QaU7XGjWEHEgj9J+6AhUtDWJ2yqZI02sK/Dg2eF5NR0hJ5SjIzGdUan9innEgl5hMegzyMUgipwowNwJECKxU2SUQYL75fuZMS5vE9X+DxfHxfevOtUz4OpTeYR8BSQkVUCFR1ctcU4gDRALLc8us1OOjAMa3WinBhL20am8fN3g/tl0BkChXbR5V0Eeno8DWDJaot65NahbbzbZKwyEcQyuH1Vzwok1+Yrh+pJgKOstjq2kW1rb/AthSTrtOcR1WM5r7XUha/momu2E2T8pJG9YaEpBCHQexucPzdiRDnM5uTooQufx+idGT93dHCt96j9Hpbj84/0wpXKwNLaVP2ZpjcBX4MStauBtmYJdMhhBzrA=
    github_token:
      secure: E9RFVrCmEzphD/FWz/aIuzazK2iZE+lmIZ+qcvIo78ndEelvJQ0/VtkyvclBpKcFBQc+AJJpke6CAprEyCvz8Puj4L9XbSkRDhz5PGBfB8gxTDqgkrUpH3KVGqWx1/KJ/KjkZgMNb4FHwqD0vmlxnhAkdwwyRWzcdWUjqluwY0xQbbvJ7vS7BoJAmf5MLyb0Q65nW6NhGfSf16fNSACnp4Xbd3VdfGAOQL9X01dKVTV0GAPMrqs+QKhKOvZC/fRT0qXLXKyGqYc/nyoBwFZGBwSykdTDXZwR+ylnbRNgHRZxoBsmjscskeDf2kgKvTxkXbF3Ij1utBb7n0ocCN43lt5l4cZEdyDfuwzY+eeDHF61SWs42cKfef5fmsb2wb3Vel/+HnYs9grYdAOG0RcpIioll2Tj5CLWSbIJfhBuq1cQA3mu6m3klj+IM4D2HVBXlMF9c6YqlyCKJ4w5Kd+Q4K5THcARulXZdjHqk173/Ud2CgCqpsjSkvIMHReuyuijDUcRk4BTBGDipeDbF4sPcoaZX2MwNxnULMbi4D8WJr78w0IZ3kC1zSFXlmw0mSxothdjXL0jAMyQi28vKMW4YX+yAXgbIf/Wmg8sfe2nHw9RpE3PakQZwg+++QU7Rfv930LSf2Fg0s0vcSDWsAsM0nwAo4l/ONrHDiC/IDyYbBw=
