dist: trusty
sudo: required
jdk: oraclejdk8
services:
- docker
script:
- bash test/travis-bin/run-tests.sh
- bash test/travis-bin/sonar.sh
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
addons:
  sonarqube:
    branches:
      - /.*/
env:
  global:
  - secure: hE0QOdmV0YmD9seoxiRa/5dWMATfhAs083b6iqq9dMQwB9fh65l32kr0woKES91tfmUejf22VPrb2Gge8uijFpGySiwWO5pUiVc+Lgtr/vF6zKgyASxdH3IJ4wstNcsR2jjRfmBStiDx5eNJOBx2vlo9gtFvB2p9176GKnj66flANEb7mt5+ak9xVOZ4gf9PpQBzlnX7a3Y1M18dvySHWNSbGwHMdn2EcljjqZGBcvBRALRIDQVf1gYBxBT6WUzUjeHouR+oM5bd5iOdmJfOSj/bMnsUhUrTBndDdEEwLAAbwEAkfy17HX8SeiiIlepm4PHcgZnJp92jzRX97/61zu03pwBMU7qRvzDCZYQl6Hy2sXNoP7Bp4ztJvgiLYe6lskrJslihVMozN6q1GZKFB4cppwqzJIGPzMXj3UbgWvgv2lC81dVlxLh/GYRHyDW9zRMTBOAN7sPb76gEXTpUgnUrIzacYR99ZwQ5Cyh/4ChW6tK7eT+UmgAR+PaCalZppf11hlyYcFhW2Gbcf2CW/BkzAqZsZpnnETJ9h0hBykG0cwj0nnEHESmntvVtAfXagjobJO1D+p0w9jQg+M9FRjpilXXZIYgJVVAy5K/4xB5JuB/WmSMH3ypzcmOTj2ULySCbNmRCPiJCdhcXeI9dU5DyDV19+VK1nAYfEjrPH04=
  - secure: pEf0vreXk4TZTPfWh+534sTqSYI7fy+ddulpOUsv7AqC5Jpbi8QKImlMBCZK3Qp6Hsq9c5MsHNdc+HH/TGRoJo8NIKAhLg4HKYjt464k5cYiG/FF/yiNUgFhTnq0bUdOksd9txTuCa50lSbAdWhS2XrjDdy3R0CB3k4kY1AvYGpCKdjR6ChGeeXQXBvPR58/f3iaBKV7GpPMWeDxDaijhITWYqJfpU3UoP5k837qFCidaZXKlN/rjjlaZerDqUljvI3NwEDgTJDWTHJbH4riUvUs5vmD+xyJzDsEF44QlvonNpRm32dWFBlGnf+301DbpcpLbz0HS+fNBrPP86GSMKaLG82jY2c2w0E4HPMlOg+P2GuRqP0Lh2+JPHajyGaTdocz+RPoGYkAdnnnE+uAQI2H+6fWO3j5C86tS51IKhINZxXhNxZiU10qNr4Xyevc5uwiDyA8lCpyMaJ6talwRi5qOe7/rqoKI7S3iuNTlVgWaeIH2F3d1Ed8q8rQUIAg7B2+9JPD+TNgWSQN/5Mu4qhZCZsSpA2sQakQBsRCguKWh+6cQ8DLvzEPmbt8fDEXtRb06K0iHpjNPCdrt/ghthYSxlUR0iRCCv2eNAoRKXKbUDGUQSWZSmZo00pC7dsXga4By6Up3DEBC0PGpyfRa4kW63+kV/4KATx4q+iDD5w=
