dist: trusty
sudo: required
jdk: oraclejdk8
services:
- docker
script:
- bash test/travis-bin/run-tests.sh
- sonar-scanner
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
addons:
  sonarqube:
    branches:
    - master
    - "/.*\\.x$/"
    token:
      secure: Ke1YeIgYseFQ2xxwVWR4+iNYxov3n1mvfTe/5cOQdkw0WNHdnmzwtQkGJoDAIhLHbxdDJtVdvj7xty4Dazq4UlsZbaEqVoiRcVElA7jFUcseC7iv6uLkI4COIgWiHE1NuyArVvdvDl3J70S5VIXqWTnSlPIYG2EO8ADFjzBcCBLrjOeaEle22XhZWqwwxIA4r7Z9VRbqNnQF884Dy5p3Dt9PP9qx8ctNlzuOIZ9yb5IWrdlg2+XxbAZ6q6KoPyAarviUKSPfdcjkcUwX7xq9zCOTmzSlVcjH8/9aRR3xw1tnyxR6JtQ7+UDHBVaNzCdQjB63Ie5tj+eg79tCRPbVXRWGYYMat2O+JFT7WLJ5LokTMfPI0yLWN6KleRrzLTokESNeHKR+SOdVx2hw5PacDJkhDEvf43n/GpTLlZeWhz2jLbdgXzYE6L4Lh3ArRe2c60aslfgXSeaXVonyVl5t/UX71yhvEJqJJ32sBAuXjVXdJw4ZULweSJRwsLYE2zttrxcix66IOrPjzCkdeuloGTfpVRHB7Fc5x2Rz8in7ps6VJp2AP971lCfemlbaK69jzO9OnlgdIH7OYfW/etYnClr93o5xssSR1Jw9lfPL+29I4lFlr0P+FJt/Sox4Zk5RCLEZaPEpWXCzm9+ZgVjyyeSF0N0C+rKGxffHwd3tvio=
    github_token:
      secure: qxGf5ElHstt56DyFG8qyzEcbOCMuwceemHi7LjZmtCAlkbfBioHrBN2HiwoVChn+XAroHyStR3rfJedFJv+p8Nm8BkC5XUtp1n4MGHx2Zon4VxyKh11UiHc6tC4h1hqRPC27ugyPxheXKxopIBR7LXm9wGsobgROK3ilOENyp23DovC51T124z+AYI2uQihj7q9rub75MCJlkf84fgq3t0gUWEqm5fYg9f3rKkSPibSF14j4JUFWI3Wt5XKuBQFI60WJzOy+IxunI30p7zjX7MWuFFhFJcGUyKmsS7ZOZPjGuNFR4v2xAczTG7II/VtM2ZEMWYpvRfbVUCLz4MG70buMvZi6DMUbQ7nCYrH76FMrC7gWXIWT07km8WDI6CvUY60NU+6IQjX44PkHBfX4kH7OwwUE9D7EWbz6MkCRHgmhXJAT8VhK4pAQT+rDtcD5FzZ3QPJ2Dq4u+nPAN30Auy0oE7nuS+F0HAFaeKWivomSQtpxyDx4BI5aoZRbnsTnzOM9rlKY407fFuwa6Ug656IvgXRq0M+iK9nuEmP+9CyDswwEHmpnqF9gwy5ZgbhL4hgucoNzG6j3jULDfEk5hfmUFYHv2I/YcvdzGdygmYmZsLtjyq5mIQD4ZK+/USyjcch7huT7pxAAAsaSJy+2I3sBdu00O00E9y3Ehq6LawU=
