dist: trusty
sudo: required
jdk: oraclejdk8

services:
  - docker

script:
  - bash test/travis-bin/run-tests.sh
  - bash test/travis-bin/sonar.sh
  
cache:
  directories:
    – $HOME/.m2
    – $HOME/.sonar/cache

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never

addons:
  sonarqube:
    branches:
      - master
      - rc.x
    token:
      secure: BM+uIcn3x36YOQG1AN9XxKEHn5f5NejhWw3SAsxk4JsdFzOSPO67PBoJ8ACM8vl0Y0/f/zUIg0iYxd91NTTjhPSfXF3x6QZBDWwXwRQmLjBmwWS17QC7GbqTuAJ4/CXASxjntcsebT7FpRXx8apUVwW3CbB4f4Y8nf0No0Okq73fvcRejedCD0pC1L7n7H5X4xXJ+/CfXVnUc0jUZkMa5x2umEbSfGz27X7uqvfGkjMTAdzO7aQTBei423Y+sqG1U0thJepipxlEfaFR4r9tJ0qc6oIZsUMXn6ywjFNhNPvKImmLSvVlUFzINFotKtNr9AQiBjISOqRUhVLOm8tWAoLlQtm0mO1jsLQ68MrYPKPpb1ZZfXneRtxiWlZqSgGiU8fs7mxjOyfBIhk+avDpVNIS5QP0n1UhfEhBeOOkXl+zqqnbu4GMxnkVfI4zToLxYS+mpC8WWGZTbNoGhRPh5I4tfqc1YvQ4UzBz8rBO5yJOLyiaNd9py51zSXhfDZcv9786EqUX9m/ZixNyB2ncPQGgx5wbePD4cd8+5LC9Or0EAbba/QM4TbYS9XQ0iVnwT7PjnN3wc/twWhifVu1Zuwnh6YUxovhmU2jveN/hE+UwGT6Ls65cSFl3ar1Y03Q75sh69SvN1kGJUpL5EVQpcmFT5m8lCUumI1BVfYMICgg=
    github_token:
      secure: Dg9fFhRkuRLgZRJHWWnZ341gASYDuf5wg0VJ8uGEsKiic45SKwj0DAm6d/XqRLAtXznaR+65LaCRAZDgWTlFlExTXvUDgBPcc3oUhwDGjcK1q03ArV+13wlADuxTtbft5Zz5r4k/01i+EfX6a+ehg7ZDM1jEdPqiXheQjmcumVSnJjtz5cApYgQBTjztA9wYImxSpEiUqDwfOHzZQvtHUSkt00NadnvbLn8ZYlqwhsjihy36aaVmkiME4SwC71Y8Sp9OvHUJbgSEV24hQtB2ExQF9XSFfUch6VbbWO9E9JmIcNwIzSa8/gUdQyQU92sSP9Uh6o993MokHHkZ9pXkpIJyoTgac4b6CSMAYA+BPadvKyjVeFx7qS3caxDB38qvasW0raMAGzzuNwEOdOd0nxDZDMfGcLBIW+FfG3cjZQMognotMTRTzjuHxfuP7+gw5809hLak63tvDrAFenKL8tcQChRiJ2nVqcrrly59EX1jhRWdZR2GS0BGpcbX1s/49Jyieriwo/VKt+fhaZPjtyvGNwJFVekBUrPJ7lgBgPB/UfbbaG7iRPU7YCZg4MwFtuvVcXfCpz26IEFvhEr3Opwhg+N+GJdnlUusmRjXtdDTmTNdoEurhR4zHMrLPrKQ/BagdkyrZefsFf/zMqhv8wTfW2vI16tnZYO7tV28uTg=
