dist: trusty
sudo: required
jdk: oraclejdk8
services:
- docker
script:
- bash test/travis-bin/run-tests.sh
- sonar-scanner
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
addons:
  sonarqube:
    branches:
    - master
    - rc.x
env:
  global:
  - secure: G52W6MYF9weiwehtRj/KDPS+BLRCufAELZrggDfX8GSMGkmtrlEUufhCVC4ZgSbKyhfHXWHlWhjhANbrzkRf6wgDAvTrHAbthaiu9iAF6fH8zIMweYAoTVCLoE152/Pf+8Q0Kp/KuogvtCb9irRjB5/PUiFvbqjOCIEVVG6EWNAHboTT5cVAF9hRToiBk2XOAlMphsXdtDOXZytF5qHe6vdtWyDIE6idChbCTdkrD5Jf4Sjysy3MLEnDmR3VrAXVwRaPTkUg+lxO4kTXc7HuxxgY1O+EuGUDmyi9oPfEaX5u+oVCvWnOO57jR43cnHypIE+8ecaoKmPz6/WiQnlFHwta0cVnu95kmngjpUU9RwY2bVjX6FpIUTsWUyMmG8k9q2CzzgtR9ZBFl7r5d6tLKhX2wgnQAHTB3RY2MCzztjkBJgHGPdKCnwnO97geNVqin0Q3vQL0/LmxkNNUbMcXDFrPKEHEggXMmDMcv3D6UodVIH2pQK6SyjOpR3XIhxrO17a/JH7a9daMFuVFV9we26bTQD+urCIE+H/RfJdoERDVuzjBt6aEX/r7IT2M2C4gy1bUgU6fbWDkHvNpnCGnk0x5HY9US8tVfTSaMcPGyWGFskyLFe3GoKD1+hfgw5LYrkdlfuWjiWepUj5HIUUdwmJxnrptQwHohtuP97sqMc8=
  - secure: j7Lmfbni9ibywyLVoCSdQWE8flKEtP7L7R88xa25dvl5orV6IhSywMknGBC9B/TTaq3X14vkrLrbYas37oA7nM85PZ2EZz48bLdco7tU1y95q7vMxSXpgrG/3Q7Sklw0RQA+5RphDW4qmJ6lMEsuSMGvefOV6sJ6MjdPR8h4l4ehPIIpvaqwh0J49EBjZ8chMucuUfRtPh1qogZEgrDOOAAnYFVgjOX9GL/HpyPd5e2Z9lyjJOFHjHUMGbTo5cdPPVK6ne/7BjbuW4w0uMaSZ7IGXnMZDqj97ai2oTh4iwhsqYJg5aGt1KN9Br4fGsCB9Xul2i/G2K08veWtt+lxkDeKNN+IHOf2szYjRKWwAv7Q4nGvVI4sAfJsixC3mrsF0m//LPndd4p1fLyUPfiz8DMPpdrVZbobv7RL7+RPfirMa5Xmc75zpeHTCeDZqJFHkolisqfJUKn8nIZXPoKqriLFjCVTvu+xv2uifyy4XG90R5aoneDSqDE44OdVDP3aR6rMmXpH5FqkxTCImMx6PxogalrtjICsIRkhrUlyC2mGgdWu07kD7yGjl1MKsHmnEBB2w2oQ1s/BkodFE7ZVX7NojgSUDfxi59dfc4/oZDKFVOQ8GQpLEUs7QRQIwDlY95IMm+iFc3M0xRBrQ5hCW37H3YLRuu8+UsdifRc9MVU=
