kuzzle:
  image: kuzzleio/kuzzle:dev
  volumes:
    - ".:/var/app"
  ports:
    - "7512:7512"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - KUZZLE_PORT=7512
    - BROKER_HOST=rabbit:5672
    - READ_ENGINE_HOST=elasticsearch:9200
    - WRITE_ENGINE_HOST=elasticsearch:9200
    - NOTIFICATION_CACHE_HOST=redis:6379
    - LOG_ENGINE_HOST=logstash:7777
    - PM2_OPTIONS=--watch --ignore-watch npm-debug.log
    - KUZZLE_MQTT_URL=mqtt://rabbit:1883
    - KUZZLE_AMQP_URL=amqp://rabbit:5672
    - KUZZLE_STOMP_URL=stomp://rabbit:61613
    - NEW_RELIC_HOME=config
    - NEW_RELIC_LICENSE_KEY=5b64c263ffde4506e41ef969ed1c429d7e4e1c74
    - NEW_RELIC_APP_NAME=Kuzzle-dev
    - NEW_RELIC_LOG=stderr

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
