kuzzle:
  image: kuzzle
  command: /run-debug.sh
  volumes:
    - "src:/var/app"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - rabbit
  environment:
    - KUZZLE_PORT=8081
    - RABBIT_HOST=rabbit
    - PM2_OPTIONS=--watch

rabbit:
  image: kuzzle_rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
