kuzzle:
  image: kuzzleio/kuzzle
  ports:
    - "7512:7512"
    - "7513:7513"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN
    - FIXTURES
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
