proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC4
  links:
    - elasticsearch
    - redis
    - proxy:api
  volumes:
    - "./docker-compose/scripts/run.sh:/run.sh"
    - "./docker-compose/config:/config"
  environment:
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
