kuzzle:
  image: kuzzle
  command: tail -f /dev/null
  volumes:
    - "src:/var/app"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - KUZZLE_PORT=8081
    - RABBIT_HOST=rabbit
    - REDIS_HOST=redis:6379
    - PM2_OPTIONS=--watch

rabbit:
  image: kuzzle_rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
