loadbalancer:
  image: kuzzleio/lb:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

kuzzle:
  image: kuzzleio/kuzzle
  links:
    - elasticsearch
    - redis
    - loadbalancer
  environment:
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
