kuzzle:
  image: kuzzleio/kuzzle:dev
  volumes:
    - ".:/var/app"
  ports:
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
    - logstash
  environment:
    - KUZZLE_PORT=8081
    - BROKER_HOST=rabbit:5672
    - READ_ENGINE_HOST=elasticsearch:9200
    - WRITE_ENGINE_HOST=elasticsearch:9200
    - NOTIFICATION_CACHE_HOST=redis:6379
    - LOG_ENGINE_HOST=logstash:7777
    - PM2_OPTIONS=--watch
    - KUZZLE_MQTT_URL=mqtt://rabbit:1883
    - KUZZLE_AMQP_URL=amqp://rabbit:5672
    - KUZZLE_STOMP_URL=stomp://rabbit:61613

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2

logstash:
  image: logstash:1.5.2
  volumes:
    - ./logstash.conf:/config-dir/logstash.conf
  command: logstash --verbose -f /config-dir/logstash.conf
  ports:
    - "61614:61614"
