kuzzle:
  image: kuzzleio/kuzzle
  volumes:
    - ".:/var/app"
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN
    - FIXTURES
    - DEFAULT_MAPPING

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
