# HAProxy uses a self signed certificate. You have to accept the exception
# in your browser. A proper certificate should be used for non development purposes.
# In this setup, all exposed ports are using SSL.
haproxy:
  image: haproxy:1.6.4-alpine
  volumes:
    - "./docker-compose/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    - "./docker-compose/haproxy/snakeoil.pem:/etc/ssl/private/snakeoil.pem"
  ports:
    - "7511-7513:7511-7513"
  links:
    - proxy

proxy:
  image: kuzzleio/proxy:1.0.0-RC6

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC7
  links:
    - elasticsearch
    - redis
    - proxy
  environment:
    - kuzzle_services__db__host=elasticsearch
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_services__proxyBroker__host=proxy

redis:
  image: redis:3.2-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
