kuzzle:
  image: kuzzleio/kuzzle:beta
  ports:
    - "7511:7511"
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN
    - FIXTURES
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:1.7
