proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
    - "7513:7513"

kuzzle:
  image: kuzzleio/kuzzle
  links:
    - elasticsearch
    - redis
    - proxy:api

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
