kuzzle:
  image: kuzzleio/kuzzle:dev
  volumes:
    - ".:/var/app"
  ports:
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - KUZZLE_PORT=8081
    - BROKER_HOST=rabbit:5672
    - READ_ENGINE_HOST=elasticsearch:9200
    - WRITE_ENGINE_HOST=elasticsearch:9200
    - NOTIFICATION_CACHE_HOST=redis:6379
    - PM2_OPTIONS=--watch

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2