proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
    - "8083:8080"

kuzzle:
  image: kuzzleio/dev:alpine
  volumes:
    - "..:/var/app"
    - "./scripts/run-dev.sh:/run.sh"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
