proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "5713:5713"
    - "7511:7511"
    - "7512:7512"
    - "8083:8080"

kuzzle:
  image: kuzzleio/dev:alpine
  command: /run-debug.sh
  volumes:
    - "..:/var/app"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
