proxy:
  image: kuzzleio/proxy:1.0.0-RC6
  ports:
    - "7511-7513:7511-7513"
    - "8083:8080"

kuzzle:
  image: kuzzleio/dev:alpine
  command: /run.sh
  volumes:
    - "..:/var/app"
    - "./scripts/run-dev.sh:/run.sh"
    - "./config:/config"
  ports:
    - "8080:8080"
  links:
    - elasticsearch
    - redis
    - proxy
  environment:
    - FEATURE_COVERAGE=1
    - kuzzle_services__db__host=elasticsearch
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_services__proxyBroker__host=proxy


redis:
  image: redis:3.2-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
