kuzzle:
  image: kuzzleio/test:alpine
  command: /run-test.sh
  volumes:
    - "..:/var/app"
  ports:
    - "7511:7511"
    - "7512:7512"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE=1

rabbit:
  image: kuzzleio/rabbitmq:alpine
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
