proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
    - "7513:7513"

kuzzle:
  image: kuzzleio/test:alpine
  command: sh -c '/run.sh; npm run codecov'
  volumes:
    - "..:/var/app"
    - "./scripts/run-test.sh:/run.sh"
    - "./config:/config"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FEATURE_COVERAGE=1
    # Travis env var must be propagated into the container
    - TRAVIS
    - TRAVIS_COMMIT
    - TRAVIS_JOB_NUMBER
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
