proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511-7513:7511-7513"

kuzzle:
  image: kuzzleio/test:alpine
  command: /run.sh
  volumes:
    - "..:/var/app"
    - "./scripts/run-test.sh:/run.sh"
    - "./config:/config"
  links:
    - elasticsearch
    - redis
    - proxy
  environment:
    - FEATURE_COVERAGE=1
    - kuzzle_services__db__host=elasticsearch
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_services__proxyBroker__host=proxy

redis:
  image: redis:3.2-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
