proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

kuzzle:
  image: kuzzleio/test:alpine
  volumes:
    - "..:/var/app"
    - "./scripts/run-test.sh:/run.sh"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FEATURE_COVERAGE=1

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
