proxy:
############# UPDATE TO kuzzleio/proxy:alpine
############# WHEN RELEASING RC5
  image: kuzzleio/proxy:develop
  ports:
    - "7511:7511"
    - "7512:7512"
    - "7513:7513"

kuzzle:
  image: kuzzleio/test:alpine
  volumes:
    - "..:/var/app"
    - "./scripts/run-test.sh:/run.sh"
    - "./config:/config"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FEATURE_COVERAGE=1

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
